development:
  host: localhost
  database: <%= ENV['DATABASE_NAMESPACE'] %>_development

test:
  host: localhost
  database: <%= ENV['DATABASE_NAMESPACE'] %>_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URI'] %>
